### ISSUE TITLE
Preprint JC GitHub Pages

### ISSUE THREAD

**Issue by dasaderi** [SamanthaHindle/preprint_JournalClub#2]
@SamanthaHindle I'd like to make a github pages for our project. I learned a bit on how to do it. Maybe we can skype sometimes next weekend and I can show you what I learned?

**Comment by SamanthaHindle** [comment]
Yes, it would be great to have a github website page for this project. Let's chat about this on Monday and see if we can get it up and running before the Global Sprint launch
