### ISSUE TITLE
Community Opinion Survey

### ISSUE THREAD

**Issue by SamanthaHindle** [SamanthaHindle/preprint_JournalClub#3]
I've added some potential questions that I can send out to the community to gauge interest in Preprint JCs. I wasn't sure whether to make the file in [Markdown](https://github.com/SamanthaHindle/preprint_JournalClub/blob/master/Community%20Opinion%20Survey.md) or as a [.txt file](https://github.com/SamanthaHindle/preprint_JournalClub/blob/master/Community%20Opinion%20Survey), so I did both. What would be the best way to format this and to collect the answers? What are you doing for your Why Not Open survey? Let me know what you think to the questions and I will try and get this sent out to the ASAPbio ambassadors and others in the community asap.
Thanks!!

**Comment by dasaderi** [comment]
I don't think having a survey in the github is the best way to get responses. It's a bit hard to do a survey in markdown. We can take those questions and put them in a google form though and then link to the survey in the github.

**Comment by SamanthaHindle** [comment]
Done! Let me know what you think to the questions and the description at the beginning (or feel free to change it). Thank! :)
