### ISSUE TITLE
 Preprint Review Worksheet

### ISSUE THREAD

**Issue by dasaderi** [SamanthaHindle/preprint_JournalClub#5]
We want to create a template/worksheet to guide Preprint Journal Club leaders write reviews to send out to authors of the discussed preprints.

**Comment by SamanthaHindle** [comment]
We created a draft document for the Review Guidelines/Feedback Worksheet. You can find it [here](https://docs.google.com/document/d/1hpPdQPCZH2p8jNYgkL8CAiz3NN3BjUjhvyoWfl4eo8w/edit?usp=sharing). Please use the "Suggesting" mode to suggest edits, so we can see what changes have been made. It would be helpful if you log in to your Google account so we know who made what changes; this will allow us to send you a big THANK YOU!! Please write questions/comments here if you have any. Thanks!

**Comment by amiefairs** [comment]
I suggested some changed to your worksheet! Unfortunately I could only edit the link above and not even change it to suggesting, so I created a copy of the worksheet and suggested changes to that. The link is https://docs.google.com/document/d/1RmH0yhNtL0l75zYtwCELbaiRRwgyfXAVHu-SceMlyCM/edit?usp=sharing

I hope it is helpful! I really like the worksheet so far, I think it is very comprehensive. I remember somewhere on twitter seeing a 'guide to peer review for PhDs/ECRs' and I searched for it but couldn't find it... Maybe you guys have seen it? If you haven't, it might be useful in case there are areas you might want to address but have slipped your mine :)

**Comment by SamanthaHindle** [comment]
Thank you so much Amie! Your comments are super helpful. I'm sorry you weren't able to change it to suggesting mode, but thank you for creating a new one.

Yes, I saw the twitter article too and was planning to find it today to add to the worksheet. If I manage to find it, I will share the link here. 

Thanks again for your help. I really appreciate it!

**Comment by KirstieJane** [comment]
Heya! I looooove this project ❤️ 

Here's the [Publons Academy](https://publons.com/community/academy/) curriculum.

And here's a fantastic blog post by [Duncan Astle](https://twitter.com/DuncanAstle) & [Sue Fletcher-Watson](https://twitter.com/SueReviews): http://www.dart.ed.ac.uk/try-peer-review/

**Comment by SamanthaHindle** [comment]
Thanks you soooooo much Kirstie! These resources are awesome...and thanks for our chat about this!

**Comment by KirstieJane** [comment]
Heya - If this is useful here's a peer review I wrote for F1000: https://f1000research.com/articles/5-1903/v1

The point of sharing this is to show off my template: synopsis, compliments then concerns/suggestions.

**Comment by SamanthaHindle** [comment]
Here's a great list of questions that we can incorporate into the worksheet from the Publons Academy site: https://publons.com/blog/peer-review-essentials-for-the-beginning-peer/ 
by Elisabeth Bik 

Thanks for the recommendation @KirstieJane! 🥇

**Comment by dasaderi** [comment]
Thank you so much @KirstieJane and @amiefairs! You girls rock!

**Comment by chartgerink** [comment]
Just added a few suggestions in the GDoc! :dango:

**Comment by dasaderi** [comment]
@chartgerink Thanks! I'll check now.

**Comment by SamanthaHindle** [comment]
The updated review worksheet can be found [here](https://github.com/SamanthaHindle/preprint_JournalClub/blob/master/Starter_Kit/PPJC_Review_Worksheet.md). Thanks!

**Comment by SamanthaHindle** [comment]
Hey @KirstieJane. I added your review to a Google drive folder we have created with example reviews. I hope that's ok. Let me know if not. I hope you are well!
Thanks,
Sam
