### ISSUE TITLE
Preprint info sheet 

### ISSUE THREAD

**Issue by dasaderi** [SamanthaHindle/preprint_JournalClub#6]
Make an info page about preprints and their contribution to advancing scientific discovery.

**Comment by SamanthaHindle** [comment]
We haven't started a Google doc for this yet, but if you would like to work on this please feel free to create a Google doc. It would be helpful if you could share the file with the PreprintJC google account and change the settings so anyone with the link can access it (then post the link here). Thank you so much for your help!

**Comment by SamanthaHindle** [comment]
Updated info sheet can be found [here](https://github.com/SamanthaHindle/preprint_JournalClub/blob/master/Starter_Kit/PPJC_Info_Doc.md). Please let us know if it's helpful or not. Thanks!
