### ISSUE TITLE
Preprint flyer template

### ISSUE THREAD

**Issue by dasaderi** [SamanthaHindle/preprint_JournalClub#7]
Make an editable flyer template that can be used by Preprint Journal Club leaders to advertise the meeting.

**Comment by SamanthaHindle** [comment]
We haven't started a Google doc for this yet, but if you would like to work on the flyer please feel free to use whatever software you like and you can use the [Preprint JC logo](https://github.com/SamanthaHindle/preprint_JournalClub/blob/master/logo.png) too. It would be helpful if you could share the file with the PreprintJC google account and change the settings so anyone with the link can access it (then post the link here). Thank you so much for your help!
