### ISSUE TITLE
Create Preprint Journal Club Guidelines

### ISSUE THREAD

**Issue by SamanthaHindle** [SamanthaHindle/preprint_JournalClub#9]
Please help us write Preprint Journal Club Guidelines that will help scientists start their own Preprint Journal Club. These guidelines could be built using Prachee Avasthi's [syllabus](http://asapbio.org/wp-content/uploads/2016/11/Syllabus_ANAT900-1page.pdf).

**Comment by SamanthaHindle** [comment]
We haven't started a Google doc for this yet, but if you would like to work on this please feel free to create a Google doc and use Prachee's syllabus to get you started. It would be helpful if you could share the file with the PreprintJC google account and change the settings so anyone with the link can access it (then post the link here). Please post questions/comments here if you have any and I will get back to you asap. Thank you so much for your help!

**Comment by dasaderi** [comment]
Just created a doc for the guidelines in our shared google folder (https://drive.google.com/open?id=0B35ExB2V98ZaeDdIQkRLQ3Jianc). It's still empty, but you can help us fill it in. Right now it's just a brainstorming space, so don't worry about adding stuff that just comes out of your head. Thank you! https://docs.google.com/document/d/1DbqqS_8MOWz4duzkSZBl_wMrWoyWhV-w9265eM2Ys98/edit

**Comment by dasaderi** [comment]
In the docs we can write down text that then we can use to make pretty sheets to send around. :)
